--- 
title: "Auto Formation R avancé"
author: "Le groupe State Of The R in Roscoff"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "Ceci est le résultat d'une semaine d'auto formation à R."
---

# Introduction 

## Objectif 

Le groupe State Of The R (SOTR) s'est réuni  à Roscoff du 28 août 2017 au 1$^{\mbox{er}}$ septembre 2017 pour une semaine d'auto-formation autour du logiciel R. Différents sujets ont été abordés durant cette semaine 

  - Utilisation de git (surtout GitHub, Chaptire \@ref(github) ) 
  - Automatisation et reproductibilité du code : ``rmarkdown`` ( Chapitres \@ref(rmarkdown), \@ref(blogdown), \@ref(bookdown)),
  - Manipulation de données :`` tidy`` (Chapitre \@ref(tidyverse))
  - Programmation orientée objets : ``R6 class`` (Chapitre \@ref(R6)),
  - Aspects techniques : Production de packages, ``Rcpp`` (Chapitre \@ref(packages)). 


Nous avons travaillé avec `R` (3.4.1) et  `Rstudio`  (1.1.350) sur les plateformes 
linux (ubuntu version > 15.04), macosx (Sierra 10.12.6), windows (7).

Ce livre résume les expériences des participants durant l'atelier. 

## Ressources principales 

  - [http://rmarkdown.rstudio.com/](R Markdown website)
  - [https://bookdown.org/yihui/blogdown/](blogdown: Creating Websites with R Markdown)
  - [https://bookdown.org/yihui/bookdown/](bookdown: Creating Books with R Markdown)
  - [https://rstudio.github.io/learnr/](Interactive Tutorial with R)
  - [http://r4ds.had.co.nz/](Le livre R for Data Science)
  - [http://adv-r.had.co.nz/](Advanced R)



## Les participants 

  - Christophe Ambroise
  - Julie Aubert
  - $\pi R$ Barbillon
  - Séverine Bord
  - Mathieu Carmassi
  - Julien Chiquet 
  - Jessica Cosmao-Tressou
  - Sophie Donnet 
  - Marie-Pierre Etienne
  - Marie Perrot-Dockes
  - Timothée Tabouy


```{r, include=FALSE, eval=TRUE}
# automatically create a bib database for R packages
knitr::write_bib(c('base', 'rmarkdown', 'blogdown', 'bookdown', 'knitr', 'devtools', 'tidyverse', 'tidyr', 'dplyr', 'purrr', 'ggplot2', 'R6', 'roxygen2'),file='packages.bib')
```